language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn install
  - yarn test
deploy:
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
  provider: script
  script: bash ./deploy_to_aws.sh
  on:
    branch: develop