matrix:
  include:
    language: ruby
    ruby:
      - "2.6.3"
    services:
      - postgresql

    before_script:
      - psql -c 'create database tictactoe_test;' -U postgres

    script:
      - bundle exec rake db:migrate RAILS_ENV=test
      - bundle exec rake spec

    language: node_js

    node_js:
      - "stable"
    cache:
      directories:
      - node_modules
    script:
      - npm install
      - npm test
    deploy:
      provider: script
      script: bash ./deploy_to_aws.sh
      on:
        branch: develop
    addons:
      ssh_known_hosts:
        - ec2-52-38-40-75.us-west-2.compute.amazonaws.com
        - 52.38.40.75