version: "3.0"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PASSWORD: "psql"
  web:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psql"
      POSTGRES_HOST: "db"
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-postgres.sh", "sudo docker-compose run web bundle exec rake db:create", "docker-compose run web bundle exec rake db:migrate", "bundle exec rails server -b 0.0.0.0"]
    ports:
      - "80:3000"
    depends_on:
      - db
      